sudo: required

services:
  - docker

before_install: 
  - docker build -t buildntest -f Dockerfile.dev .

script: 
  - docker run buildntest yarn test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'frontend'
  env: 'frontend-env'
  bucket_name: 'elasticbeanstalk-us-east-1-930561438368'
  bucket_path: 'frontend'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"